---
abstract: 'String utilities'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SHARYANTO-String-Util
requires:
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=SHARYANTO-String-Util
  homepage: https://metacpan.org/release/SHARYANTO-String-Util
  repository: git://github.com/sharyanto/perl-SHARYANTO-String-Util.git
version: 0.26
